name: Compile on Ubuntu LTS
run-name: Ubuntu LTS Compilation Workflow
on: workflow_dispatch
jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential git python3 libglew-dev libsdl2-dev extra-cmake-modules cmake qtbase5-dev qtdeclarative5-dev libqt5svg5-dev qtquickcontrols2-5-dev qml-module-org-kde-kirigami2 kirigami2-dev libkf5i18n-dev gettext libkf5coreaddons-dev qml-module-qtquick-layouts libgit2-dev meson
          version: 1.0
      - name: Compile launcher
        run: |
          bash compile
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: |
            build/Kirigami64
